import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  Sidebar  from "@/components/sidebar";
import Footer from "@/components/footer";
import { ClientProviders } from "@/providers/clientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-dvh">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh font-robotoMono pb-14`}
          >
          <ClientProviders>
            <Sidebar />
            {children}
            <Footer />
          </ClientProviders>
        </body>
    </html>
  );
}
